### ISSUE TITLE
task3中间模块内容溢出的问题

### ISSUE THREAD

**Issue by ricosmall** [ifestudy/ife-task#3]
task3要求自适应宽度，限制最大高度。自适应宽度没问题，但是高度限制之后，还是存在内容溢出的情况（缩小浏览器宽度的时候）。求教！

**Comment by iceprosurface** [comment]
## 当前做法

目前，你使用的方法是固定高度来实现清除浮动，这样不符合题设。

## 解决方案

### 1. 固定高度

在溢出位置添加css内容

``` css
overflow:hidden;
```

 PS:这样做不符合题设：

> 改变中间一栏的内容长度，以确保在中间一栏较高和右边一栏较高时，父元素的高度始终为子元素中最高的高度

### 2.清除浮动自动撑开wrap

#### 2.1 利用固定高度清除浮动

见上文

#### 2.2 利用父元素overflow:hidden清除浮动

css内容

``` css
.wrap {
    ……
    overflow:hidden;
}
.left {
    float:left;
}
.right {
    float:right;
}
```

html内容

``` html
<div class="wrap">
    <div class="left">……</div>
    <div class="right">……</div>
</div>
```

PS:优点对div结构没有影响

#### 2.3 利用clear:both;清除浮动

``` css
.wrap {
    ……
}
.clear-both {
    clear:both;
}
.left {
    float:left;
}
.right {
    float:right;
}
```

html内容

``` html
<div class="wrap">
    <div class="left">……</div>
    <div class="right">……</div>
    <div class="clear-both"></div>
</div>
```

PS:任意情况下都可以使用，且其他的一些块级元素都可以做到，缺点是会对html结构产生影响，同理可以使用:after伪类来做到（但是并不是所有结构都可以使用的）
